
library(fst)
library(data.table)

# Data load
ALL_SECOND <- read.fst("source_data/R/ENHI BOTH TABLES/ALL__PS_AUG2019_v2.fst", as.data.table = T)

# Save for VSIMP <-> ANZACS
write.fst(ALL_SECOND[,.(VSIMPLE_INDEX_MASTER, MLEE_INDEX_MASTER, VIEW_ANZACS_MASTER, VSIMPLE_INDEX_2NDARY, MLEE_INDEX_2NDARY, VIEW_ANZACS_2NDARY)], 
          "source_data/R/ENHI BOTH TABLES/VSIMP_ANZACS__PS_AUG2019_v2.fst", 75)

# Save for VSIMP <-> TestSafe
write.fst(ALL_SECOND[,.(VSIMPLE_INDEX_MASTER, VIEW_TESTSAFE_MASTER, VSIMPLE_INDEX_2NDARY, VIEW_TESTSAFE_2NDARY)], 
          "source_data/R/ENHI BOTH TABLES/VSIMP_TESTSAFE__PS_AUG2019_v2.fst", 75)

# Save for VSIMP <-> External
write.fst(ALL_SECOND[,.(VSIMPLE_INDEX_MASTER, EXTERNAL_INDEX_MASTER, VSIMPLE_INDEX_2NDARY, EXTERNAL_INDEX_2NDARY)], 
          "source_data/R/ENHI BOTH TABLES/VSIMP_EXTERNAL__PS_AUG2019_v2.fst", 75)

# Save for ANZACS <-> MOH_ENHI

library(haven)

write_sav(ALL_SECOND[,.(MLEE_INDEX_MASTER, MLEE_INDEX_2NDARY, VIEW_ANZACS_MASTER, VIEW_ANZACS_2NDARY, MOH_ENHI_2NDARY)], 
          "source_data/SAS/ENHI BOTH TABLES/ANZACS_P__MOH_S_AUG2019_v2.sav")

# This save has been done on 7 November 2019 for anzres_nap_year files
write_sav(ALL_SECOND[,.(MLEE_INDEX_MASTER, VIEW_ANZACS_MASTER, VSIMPLE_INDEX_2NDARY)], 
          "source_data/SAS/ENHI BOTH TABLES/ANZACS_P__VSIMP_S_AUG2019_v2.sav")


# Alternative / Legacy Key Prepartion
ALL_ENHI <- read.fst("V:/source_data/R/ENHI BOTH TABLES/ALL_ENIGMA_ALL_INHOUSE_PRIMARY_SECONDARY_JUN2019.fst", as.data.table = T)
VSIMPLE <- read.fst("V:/source_data/R/ENHI BOTH TABLES/VIEW_VSIMP_MOH__PS_AUG2019.fst", as.data.table = T)

setkey(ALL_ENHI, VIEW_ENHI_2NDARY)
setkey(VSIMPLE, VIEW_ENHI_2NDARY)

VSIMP_STU <- VSIMPLE[,.(VSIMPLE_INDEX_MASTER, VSIMPLE_INDEX_2NDARY, VIEW_ENHI_2NDARY)][
  ALL_ENHI[,c("STUDENT_INDEX_MASTER", "STUDENT_INDEX_2NDARY", "VIEW_ENHI_MASTER", "VIEW_ENHI_2NDARY"), with = F], 
  nomatch =  0]

write.fst(VSIMP_STU, "V:/source_data/R/ENHI BOTH TABLES/VIEW_VSIMP_STU__PS_JUN2019.fst", 75)



